# Generated by Django 5.0.6 on 2024-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='path/to/default_thumbnail.jpg', upload_to='thumbnails/'),
        ),
    ]
