# Generated by Django 5.0.6 on 2024-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_portrait',
            field=models.BooleanField(default=False),
        ),
    ]
