# Generated by Django 5.0.6 on 2024-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_is_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bit_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='latency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='packet_loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='playback_jitter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='video',
            name='sync_skew',
            field=models.FloatField(default=0.0),
        ),
    ]
