# Generated by Django 5.0.6 on 2024-06-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_bit_rate_video_latency_video_packet_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='bit_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='latency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='packet_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='playback_jitter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='sync_skew',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
